### ISSUE TITLE
try out the Riffusion streamlit interface

### ISSUE THREAD

**Issue by charlesfrye** [charlesfrye/riff#1]
The [Riffusion project on GitHub](https://github.com/riffusion/riffusion) wraps a user interface around a riffusion model.

Try out some of their interfaces and get a handle for what can be done with this tool.

**Comment by Sally-Frye** [comment]
Notes from Riffusion's design:
- Very simplistic interface
- Hides more complicated settings behind gear button
- Scrolling seed image constantly disappears/breaks
- play button not in intuitive place
- include a download button
- Only settings include seed image and denoising, as an alternative to Riffusion Playground's countless settings.
- Place to see previous prompts (how necessary is this?)
