### ISSUE TITLE
add a mocker for the InferenceInput

### ISSUE THREAD

**Issue by charlesfrye** [charlesfrye/riff#12]
call all of the relevant functions -- except for initAudio

**Comment by charlesfrye** [comment]
for initAudio maybe fire off a click event?

**Comment by Sally-Frye** [comment]
Added in commit [#e992d11](https://github.com/charlesfrye/riff/commit/e992d11b6f352ff3b8eee3c7b7089390a7839865) 
Call "setPlaceholders()" in console, will be prompted to upload audio file.
